development:
  cloud_name: "associazione-mind-mad-in-design"
  api_key: "466835976245765"
  api_secret: "GOrlA7ZRRXDuxTrxUsdumHcQnmc"

production:
  cloud_name: "associazione-mind-mad-in-design"
  api_key: "466835976245765"
  api_secret: "GOrlA7ZRRXDuxTrxUsdumHcQnmc"

