meta_title: "MinD - Mad In Design"
meta_description: "Mad in Design è un workshop sul progetto dell’abitare per la fragilità mentale. Un’esperienza di progettazione inclusiva e multidisciplinare."
meta_keywords: "MinD, Mad in Design, attività di inclusione, design, inclusività, pari opportunità, disabilità, progetto, torino"
meta_image: "Madindesign_1200x628.png" # should exist in `app/assets/images/`
twitter_account: "@madindesign"   # required for Twitter Cards
