class AddOutcomesDirectlyToWorkshops < ActiveRecord::Migration[6.0]
  def change
    add_column :workshops, :outcome_1_title, :string
    add_column :workshops, :outcome_1_subtitle, :string
    add_column :workshops, :outcome_1_content, :text
    add_column :workshops, :outcome_1_display, :boolean
    add_column :workshops, :outcome_1_img_1, :string
    add_column :workshops, :outcome_1_img_2, :string
    add_column :workshops, :outcome_1_img_3, :string
    add_column :workshops, :outcome_1_img_4, :string
    add_column :workshops, :outcome_1_img_5, :string
    add_column :workshops, :outcome_2_title, :string
    add_column :workshops, :outcome_2_subtitle, :string
    add_column :workshops, :outcome_2_content, :text
    add_column :workshops, :outcome_2_display, :boolean
    add_column :workshops, :outcome_2_img_1, :string
    add_column :workshops, :outcome_2_img_2, :string
    add_column :workshops, :outcome_2_img_3, :string
    add_column :workshops, :outcome_2_img_4, :string
    add_column :workshops, :outcome_2_img_5, :string
    add_column :workshops, :outcome_3_title, :string
    add_column :workshops, :outcome_3_subtitle, :string
    add_column :workshops, :outcome_3_content, :text
    add_column :workshops, :outcome_3_display, :boolean
    add_column :workshops, :outcome_3_img_1, :string
    add_column :workshops, :outcome_3_img_2, :string
    add_column :workshops, :outcome_3_img_3, :string
    add_column :workshops, :outcome_3_img_4, :string
    add_column :workshops, :outcome_3_img_5, :string
    add_column :workshops, :outcome_4_title, :string
    add_column :workshops, :outcome_4_subtitle, :string
    add_column :workshops, :outcome_4_content, :text
    add_column :workshops, :outcome_4_display, :boolean
    add_column :workshops, :outcome_4_img_1, :string
    add_column :workshops, :outcome_4_img_2, :string
    add_column :workshops, :outcome_4_img_3, :string
    add_column :workshops, :outcome_4_img_4, :string
    add_column :workshops, :outcome_4_img_5, :string
    add_column :workshops, :outcome_5_title, :string
    add_column :workshops, :outcome_5_subtitle, :string
    add_column :workshops, :outcome_5_content, :text
    add_column :workshops, :outcome_5_display, :boolean
    add_column :workshops, :outcome_5_img_1, :string
    add_column :workshops, :outcome_5_img_2, :string
    add_column :workshops, :outcome_5_img_3, :string
    add_column :workshops, :outcome_5_img_4, :string
    add_column :workshops, :outcome_5_img_5, :string
    add_column :workshops, :outcome_6_title, :string
    add_column :workshops, :outcome_6_subtitle, :string
    add_column :workshops, :outcome_6_content, :text
    add_column :workshops, :outcome_6_display, :boolean
    add_column :workshops, :outcome_6_img_1, :string
    add_column :workshops, :outcome_6_img_2, :string
    add_column :workshops, :outcome_6_img_3, :string
    add_column :workshops, :outcome_6_img_4, :string
    add_column :workshops, :outcome_6_img_5, :string
  end
end
