class RemoveColumnsFromWorkshops < ActiveRecord::Migration[6.0]
  def change
    remove_column :workshops, :outcome_1_title
    remove_column :workshops, :outcome_1_subtitle
    remove_column :workshops, :outcome_1_content
    remove_column :workshops, :outcome_1_display
    remove_column :workshops, :outcome_1_img_1
    remove_column :workshops, :outcome_1_img_2
    remove_column :workshops, :outcome_1_img_3
    remove_column :workshops, :outcome_1_img_4
    remove_column :workshops, :outcome_1_img_5
    remove_column :workshops, :outcome_2_title
    remove_column :workshops, :outcome_2_subtitle
    remove_column :workshops, :outcome_2_content
    remove_column :workshops, :outcome_2_display
    remove_column :workshops, :outcome_2_img_1
    remove_column :workshops, :outcome_2_img_2
    remove_column :workshops, :outcome_2_img_3
    remove_column :workshops, :outcome_2_img_4
    remove_column :workshops, :outcome_2_img_5
    remove_column :workshops, :outcome_3_title
    remove_column :workshops, :outcome_3_subtitle
    remove_column :workshops, :outcome_3_content
    remove_column :workshops, :outcome_3_display
    remove_column :workshops, :outcome_3_img_1
    remove_column :workshops, :outcome_3_img_2
    remove_column :workshops, :outcome_3_img_3
    remove_column :workshops, :outcome_3_img_4
    remove_column :workshops, :outcome_3_img_5
    remove_column :workshops, :outcome_4_title
    remove_column :workshops, :outcome_4_subtitle
    remove_column :workshops, :outcome_4_content
    remove_column :workshops, :outcome_4_display
    remove_column :workshops, :outcome_4_img_1
    remove_column :workshops, :outcome_4_img_2
    remove_column :workshops, :outcome_4_img_3
    remove_column :workshops, :outcome_4_img_4
    remove_column :workshops, :outcome_4_img_5
    remove_column :workshops, :outcome_5_title
    remove_column :workshops, :outcome_5_subtitle
    remove_column :workshops, :outcome_5_content
    remove_column :workshops, :outcome_5_display
    remove_column :workshops, :outcome_5_img_1
    remove_column :workshops, :outcome_5_img_2
    remove_column :workshops, :outcome_5_img_3
    remove_column :workshops, :outcome_5_img_4
    remove_column :workshops, :outcome_5_img_5
    remove_column :workshops, :outcome_6_title
    remove_column :workshops, :outcome_6_subtitle
    remove_column :workshops, :outcome_6_content
    remove_column :workshops, :outcome_6_display
    remove_column :workshops, :outcome_6_img_1
    remove_column :workshops, :outcome_6_img_2
    remove_column :workshops, :outcome_6_img_3
    remove_column :workshops, :outcome_6_img_4
    remove_column :workshops, :outcome_6_img_5
  end
end
